version: '3.8'

services:
  app:
    container_name: rhizome
    build:
      context: .
      target: runtime_stage
      args:
        - NODE_ENV=${NODE_ENV}
        - PORT=${PORT}
    ports:
      - ${PORT}:${PORT}
    restart: always
    env_file: .env
